"""fix foreign keys for notifications

Revision ID: 590b15851cd6
Revises: 369ab01a8f7b
Create Date: 2026-01-14 22:55:24.848459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '590b15851cd6'
down_revision = '369ab01a8f7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'tickets', ['ticket_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
